# Terralift research configuration
# DWB controller + Smac 2D A*

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    progress_checker_plugin: progress_checker
    goal_checker_plugins: [general_goal_checker]
    controller_plugins: [FollowPath]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: true
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.07

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: -0.4
      max_vel_x: 0.4
      min_vel_y: -0.4
      max_vel_y: 0.4
      max_vel_theta: 1.5
      min_speed_xy: 0.0
      max_speed_xy: 0.6
      min_speed_theta: 0.0

      # Holonomic / mecanum
      holonomic_robot: true

      acc_lim_x: 1.0
      acc_lim_y: 1.0
      acc_lim_theta: 3.0
      decel_lim_x: -1.0
      decel_lim_y: -1.0
      decel_lim_theta: -3.0

      vx_samples: 20
      vy_samples: 20
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2

      # Critics (tune these once, then keep stable for all trials)
      critics: [RotateToGoal, GoalAlign, PathAlign, PathDist, GoalDist, Obstacle]
      Obstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: [GridBased]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.25
      allow_unknown: false
      max_iterations: 100000
      max_on_approach_iterations: 1000
      max_planning_time: 1.5
      motion_model_for_search: "MOORE"
      angle_quantization_bins: 1
      cost_travel_multiplier: 2.0
      debug_visualizations: false
      publish_expanded_nodes: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: true

behavior_server:
  ros__parameters:
    use_sim_time: false
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: [spin, backup, drive_on_heading, wait]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.6, 0.6, 1.8]
    min_velocity: [-0.6, -0.6, -1.8]
    max_accel: [1.0, 1.0, 3.0]
    max_decel: [-1.0, -1.0, -3.0]
    odom_topic: /odom

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 6.0
      height: 6.0
      resolution: 0.05
      update_frequency: 10.0
      publish_frequency: 5.0
      transform_tolerance: 0.2
      always_send_full_costmap: true
      footprint_padding: 0.02
      robot_radius: 0.25
      plugins: [obstacle_layer, inflation_layer]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          clearing: true
          marking: true
          max_obstacle_height: 2.0
          raytrace_min_range: 0.15
          raytrace_max_range: 12.0
          obstacle_min_range: 0.15
          obstacle_max_range: 8.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 5.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      track_unknown_space: true
      update_frequency: 5.0
      publish_frequency: 2.0
      transform_tolerance: 0.2
      always_send_full_costmap: true
      footprint_padding: 0.02
      robot_radius: 0.25
      plugins: [static_layer, obstacle_layer, inflation_layer]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          clearing: true
          marking: true
          max_obstacle_height: 2.0
          raytrace_min_range: 0.15
          raytrace_max_range: 12.0
          obstacle_min_range: 0.15
          obstacle_max_range: 8.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 4.0

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - controller_server
      - planner_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - velocity_smoother
      - local_costmap
      - global_costmap
