planner_server:
  ros__parameters:
    planner_plugins: ["Hybrid"]
    Hybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      motion_model_for_search: "OMNI"
      tolerance: 0.25
      allow_unknown: false

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.4
      lookahead_dist: 0.6
      max_angular_accel: 3.2

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
 
