planner_server:
  ros__parameters:
    planner_plugins: ["Hybrid"]
    Hybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.25
      allow_unknown: false
      motion_model_for_search: "OMNI"
      debug_visualizations: true
      publish_expanded_nodes: true
      angle_quantization_bins: 72
      analytic_expansion_ratio: 3.5
      max_iterations: 200000

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      debug_visualizations: true
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist: 0.6

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
 
