planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.25
      max_iterations: 100000
      max_on_approach_iterations: 1000
      motion_model_for_search: "OMNI"
      allow_unknown: false
      debug_visualizations: true
      publish_expanded_nodes: true
      cost_travel_multiplier: 2.0
      angle_quantization_bins: 1

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      debug_visualizations: true
      publish_path: true
      use_velocity_scaled_lookahead_dist: true
      lookahead_dist: 0.6
      max_lookahead_dist: 1.2
      min_lookahead_dist: 0.3
      regulate_linear_velocity: true
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist: 0.6
      inflation_cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      publish_frequency: 5.0
      update_frequency: 10.0
      always_send_full_costmap: true
      footprint_padding: 0.02
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 5.0

global_costmap:
  global_costmap:
    ros__parameters:
      publish_frequency: 2.0
      update_frequency: 5.0
      always_send_full_costmap: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 4.0
